_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/content/drive/MyDrive/TransferL/DeFRCN-main/checkpoints/voc/CEVAT/defrcn_det_r101_base3/model_reset_remove.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 16
    FREEZE_FEAT: True
    CLS_DROPOUT: True
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_all9_1shot_seed0", )
  TEST: ("voc_2007_test_all9" , )
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (800,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 6000
  WARMUP_ITERS: 0
TEST:
  PCB_ENABLE: False
  PCB_MODELPATH: "/content/drive/MyDrive/TransferL/DeFRCN-main/data/pretrain_weights/ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
OUTPUT_DIR: "/Path/to/Output/Dir"